// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function EnsureOllama() {
  return window['go']['main']['App']['EnsureOllama']();
}

export function GetAllPopularHFModels() {
  return window['go']['main']['App']['GetAllPopularHFModels']();
}

export function GetCacheSize() {
  return window['go']['main']['App']['GetCacheSize']();
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetModelRecommendations() {
  return window['go']['main']['App']['GetModelRecommendations']();
}

export function GetOllamaVersion() {
  return window['go']['main']['App']['GetOllamaVersion']();
}

export function GetPopularHFModels() {
  return window['go']['main']['App']['GetPopularHFModels']();
}

export function HardwareClearCache() {
  return window['go']['main']['App']['HardwareClearCache']();
}

export function HardwareDetect() {
  return window['go']['main']['App']['HardwareDetect']();
}

export function HardwareGetCached() {
  return window['go']['main']['App']['HardwareGetCached']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function OllamaStart() {
  return window['go']['main']['App']['OllamaStart']();
}

export function OllamaStatus() {
  return window['go']['main']['App']['OllamaStatus']();
}

export function OllamaStop() {
  return window['go']['main']['App']['OllamaStop']();
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function SearchHFModels(arg1) {
  return window['go']['main']['App']['SearchHFModels'](arg1);
}
