// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {hcl} from '../models';
import {hardware} from '../models';
import {ollama} from '../models';

export function DeleteModel(arg1:string):Promise<void>;

export function EnsureOllama():Promise<void>;

export function GetAllPopularHFModels():Promise<Array<models.CatalogModel>>;

export function GetCacheSize():Promise<number>;

export function GetCurrentModel():Promise<string>;

export function GetModelRecommendations():Promise<Array<hcl.ModelRecommendation>>;

export function GetOllamaVersion():Promise<string>;

export function GetPopularHFModels():Promise<Array<models.CatalogModel>>;

export function HardwareClearCache():Promise<void>;

export function HardwareDetect():Promise<hardware.SystemSpecs>;

export function HardwareGetCached():Promise<hardware.SystemSpecs>;

export function ListModels():Promise<Array<ollama.ModelInfo>>;

export function OllamaStart():Promise<void>;

export function OllamaStatus():Promise<boolean>;

export function OllamaStop():Promise<void>;

export function PullModel(arg1:string):Promise<void>;

export function SearchHFModels(arg1:string):Promise<Array<models.CatalogModel>>;
